services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: training_facility
      POSTGRES_USER: melany
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U melany -d training_facility"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/training_facility"
      SPRING_DATASOURCE_USERNAME: "melany"
      SPRING_DATASOURCE_PASSWORD: "123456"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  db-data:
